---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sock-shop
spec:
  type: NodeType
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30656
  selector:
    name: front-end
