---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hostapp
  labels:
    app: hostapp
    chart: hostapp-0.1.0
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostapp
      release: agile-giraffe
  template:
    metadata:
      labels:
        app: hostapp
    spec:
      containers:
        - name: hostapp
          image: "willismorse/microservices-demo-microfrontend-hostapp:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}