apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microfrontend-ingress
  namespace: sock-shop
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 8080
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: hostapp
          servicePort: 8080
  - host:
    http:
      paths:
      - path: /products
        backend:
          serviceName: products
          servicePort: 8080
  - host:
    http:
      paths:
      - path: /api/catalogue
        backend:
          serviceName: catalogue
          servicePort: 80
